const resources = {
  energy: {
    label: "Energy",
    value: 0,
    maxValue: 10,
    perClick: 1,
    perSecond: 0,
    restPerSecond: 1,
    display: null,
    perClickDisplay: null,
    perSecondDisplay: null,
  },
  mana: {
    label: "Mana",
    value: 0,
    maxValue: 10,
    perClick: 1,
    perSecond: 0,
    display: null,
    perClickDisplay: null,
    perSecondDisplay: null,
  },
  focus: {
    label: "Focus",
    value: 0,
    maxValue: 3,
    perClick: 1,
    perSecond: 0,
    display: null,
    perClickDisplay: null,
    perSecondDisplay: null,
  },
  manaCrystal: {
    label: "Mana Crystal",
    value: 0,
    maxValue: 100,
    perClick: 0,
    perSecond: 0,
    display: null,
    perClickDisplay: null,
    perSecondDisplay: null,
  },
  water: {
    label: "Water",
    value: 0,
    maxValue: 0,
    perClick: 1,
    perSecond: 0,
    display: null,
    perClickDisplay: null,
    perSecondDisplay: null,
  },
  food: {
    label: "Food",
    value: 0,
    maxValue: 100,
    perClick: 1,
    perSecond: 0,
    display: null,
    perClickDisplay: null,
    perSecondDisplay: null,
  },
  wood: {
    label: "Wood",
    value: 0,
    maxValue: 100,
    perClick: 1,
    perSecond: 0,
    display: null,
    perClickDisplay: null,
    perSecondDisplay: null,
  },
  fiber: {
    label: "Fiber",
    value: 0,
    maxValue: 100,
    perClick: 1,
    perSecond: 0,
    display: null,
    perClickDisplay: null,
    perSecondDisplay: null,
  },
  trap: {
    label: "Trap",
    value: 0,
    maxValue: 5,
    perClick: 0,
    perSecond: 0,
    display: null,
    perClickDisplay: null,
    perSecondDisplay: null,
  },
  pelt: {
    label: "Pelt",
    value: 0,
    maxValue: 100,
    perClick: 0,
    perSecond: 0,
    display: null,
    perClickDisplay: null,
    perSecondDisplay: null,
  },
  stone: {
    label: "Stone",
    value: 0,
    maxValue: 100,
    perClick: 0,
    perSecond: 0,
    display: null,
    perClickDisplay: null,
    perSecondDisplay: null,
  },
  leather: {
    label: "Leather",
    value: 0,
    maxValue: 100,
    perClick: 0,
    perSecond: 0,
    display: null,
    perClickDisplay: null,
    perSecondDisplay: null,
  },
  ore: {
    label: "Ore",
    value: 0,
    maxValue: 100,
    perClick: 0,
    perSecond: 0,
    display: null,
    perClickDisplay: null,
    perSecondDisplay: null,
  },
  iron: {
    label: "Iron",
    value: 0,
    maxValue: 100,
    perClick: 0,
    perSecond: 0,
    display: null,
    perClickDisplay: null,
    perSecondDisplay: null,
  },
  nails: {
    label: "Nails",
    value: 0,
    maxValue: 100,
    perClick: 0,
    perSecond: 0,
    display: null,
    perClickDisplay: null,
    perSecondDisplay: null,
  },
  herb: {
    label: "Herb",
    value: 0,
    maxValue: 100,
    perClick: 0,
    perSecond: 0,
    display: null,
    perClickDisplay: null,
    perSecondDisplay: null,
  },
  glimmerleaf: {
    label: "Glimmerleaf",
    value: 0,
    maxValue: 50,
    perClick: 0,
    perSecond: 0,
    hidden: true,
    display: null,
    perClickDisplay: null,
    perSecondDisplay: null,
  },
  staminaTonic: {
    label: "Stamina Tonic",
    value: 0,
    maxValue: 20,
    perClick: 0,
    perSecond: 0,
    display: null,
    perClickDisplay: null,
    perSecondDisplay: null,
  },
  improvedStaminaTonic: {
    label: "Improved Stamina Tonic",
    value: 0,
    maxValue: 20,
    perClick: 0,
    perSecond: 0,
    hidden: true,
    display: null,
    perClickDisplay: null,
    perSecondDisplay: null,
  },
  manaTonic: {
    label: "Mana Tonic",
    value: 0,
    maxValue: 20,
    perClick: 0,
    perSecond: 0,
    hidden: true,
    display: null,
    perClickDisplay: null,
    perSecondDisplay: null,
  },
  huntingLure: {
    label: "Hunting Lure",
    value: 0,
    maxValue: 10,
    perClick: 0,
    perSecond: 0,
    hidden: true,
    display: null,
    perClickDisplay: null,
    perSecondDisplay: null,
  },
  staminaTonicBase: {
    label: "Stamina Tonic Base",
    value: 0,
    maxValue: 20,
    perClick: 0,
    perSecond: 0,
    display: null,
    perClickDisplay: null,
    perSecondDisplay: null,
  },
  manaTonicBase: {
    label: "Mana Tonic Base",
    value: 0,
    maxValue: 20,
    perClick: 0,
    perSecond: 0,
    hidden: true,
    display: null,
    perClickDisplay: null,
    perSecondDisplay: null,
  },
  concentratedTonicBase: {
    label: "Concentrated Tonic Base",
    value: 0,
    maxValue: 20,
    perClick: 0,
    perSecond: 0,
    hidden: true,
    display: null,
    perClickDisplay: null,
    perSecondDisplay: null,
  },
  chargedCrystal: {
    label: "Charged Crystal",
    value: 0,
    maxValue: 100,
    perClick: 0,
    perSecond: 0,
    hidden: true,
    display: null,
    perClickDisplay: null,
    perSecondDisplay: null,
  },
  crudeIronPickHead: {
    label: "Pick Head",
    missingLabel: "Needs Pick Head",
    value: 0,
    maxValue: 1,
    perClick: 0,
    perSecond: 0,
    hidden: true,
    display: null,
    perClickDisplay: null,
    perSecondDisplay: null,
  },
  ironKnifeBlade: {
    label: "Knife Blade",
    missingLabel: "Needs Knife Blade",
    value: 0,
    maxValue: 1,
    perClick: 0,
    perSecond: 0,
    hidden: true,
    display: null,
    perClickDisplay: null,
    perSecondDisplay: null,
  },
  ironAxeHead: {
    label: "Axe Head",
    missingLabel: "Needs Axe Head",
    value: 0,
    maxValue: 1,
    perClick: 0,
    perSecond: 0,
    hidden: true,
    display: null,
    perClickDisplay: null,
    perSecondDisplay: null,
  },
};

const actions = {
  explore: {
    label: "Explore",
    duration: 1,
    cost: {
      energy: 5,
    },
    unlocked: true,
    running: false,

    button: null,
    progressBar: null,
    metaProgressBar: null,

    onStart: function () {},
    onComplete: function () {},
  },

  catchBreath: {
    label: "Catch Breath",
    duration: 1,
    cost: {},
    unlocked: true,
    running: false,

    button: null,
    progressBar: null,
    metaProgressBar: null,

    onStart: function () {},
    onComplete: function () {},
  },

  recover: {
    label: "Recover",
    duration: 3,
    cost: { energy: 5, food: 1 },
    auto: { resource: "focus", resumeAfterRest: true },
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },

  gatherWood: {
    label: "Gather Wood",
    duration: 1,
    cost: {
      energy: 4,
    },
    unlocked: false,
    running: false,
    auto: { resource: "wood", resumeAfterRest: true },

    button: null,
    progressBar: null,
    metaProgressBar: null,

    onStart: function () {},
    onComplete: function () {},
  },

  gatherFood: {
    label: "Gather Food",
    duration: 1.5,
    cost: {
      energy: 3,
    },
    unlocked: false,
    running: false,
    auto: { resource: "food", resumeAfterRest: true },

    button: null,
    progressBar: null,
    metaProgressBar: null,

    onStart: function () {},
    onComplete: function () {},
  },

  gatherWater: {
    label: "Gather Water",
    duration: 1,
    cost: {
      energy: 2,
    },
    unlocked: false,
    running: false,
    auto: { resource: "water", resumeAfterRest: true },

    button: null,
    progressBar: null,
    metaProgressBar: null,

    onStart: function () {},
    onComplete: function () {},
  },

  travel: {
    label: "Travel",
    duration: 1,
    cost: {},
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },

  packFood: {
    label: "Pack Food",
    duration: 0,
    cost: {
      food: 1,
    },
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },

  packWater: {
    label: "Pack Water",
    duration: 0,
    cost: {},
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },

  beginExpedition: {
    label: "Prepare for Expedition",
    duration: 1,
    cost: {},
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },

  exploreLocation: {
    label: "Explore Location",
    duration: 1,
    cost: {
      energy: 6,
    },
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },

  gatherFiber: {
    label: "Gather Fiber",
    duration: 1,
    cost: {
      energy: 1,
    },
    unlocked: false,
    running: false,
    auto: { carriedItem: "fiber" },
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },

  gatherHerbs: {
    label: "Gather Herbs",
    duration: 3,
    cost: {
      energy: 4,
    },
    unlocked: false,
    running: false,
    auto: { carriedItem: "herb" },
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },

  gatherGlimmerleaf: {
    label: "Gather Glimmerleaf",
    duration: 4,
    cost: {
      energy: 6,
    },
    unlocked: false,
    running: false,
    auto: { carriedItem: "glimmerleaf" },
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },

  storeHerb: {
    label: "Store Herb",
    duration: 0,
    cost: {},
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },

  storeGlimmerleaf: {
    label: "Store Glimmerleaf",
    duration: 0,
    cost: {},
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },

  packHerb: {
    label: "Pack Herbs",
    duration: 0,
    cost: {},
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },

  returnToCamp: {
    label: "Return to Camp",
    duration: 1,
    cost: {},
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },

  packTrap: {
    label: "Pack Trap",
    duration: 0,
    cost: {
      trap: 1,
    },
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },
  packPelt: {
    label: "Pack Pelt",
    duration: 0,
    cost: {
      pelt: 1,
    },
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },

  storePelt: {
    label: "Store Pelt",
    duration: 0,
    cost: {},
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },

  takeLeather: {
    label: "Take Leather",
    duration: 0,
    cost: {},
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },

  packWood: {
    label: "Pack Wood",
    duration: 0,
    cost: {
      wood: 1,
    },
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },

  storeWood: {
    label: "Store Wood",
    duration: 0,
    cost: {},
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },

  packOre: {
    label: "Pack Ore",
    duration: 0,
    cost: {
      ore: 1,
    },
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },

  storeOre: {
    label: "Store Ore",
    duration: 0,
    cost: {},
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },

  takeIron: {
    label: "Take Iron",
    duration: 0,
    cost: {},
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },

  mineOre: {
    label: "Mine Ore",
    duration: 5,
    cost: {
      energy: 6,
    },
    unlocked: false,
    running: false,
    auto: { carriedItem: "ore" },
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },

  setTrap: {
    label: "Set Trap",
    duration: 1,
    cost: {
      energy: 7,
    },
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },
  checkTrap: {
    label: "Check Trap",
    duration: 1,
    cost: {
      energy: 2,
    },
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },
  scoutTrapSite: {
    label: "Scout Trail",
    duration: 1,
    cost: {
      energy: 5,
    },
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },
  gatherStone: {
    label: "Gather Stone",
    duration: 1,
    cost: {
      energy: 2,
    },
    unlocked: false,
    running: false,
    auto: { carriedItem: "stone" },
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },
  trackGame: {
    label: "Track Game",
    duration: 2,
    cost: { energy: 6 },
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },

  huntGame: {
    label: "Hunt Game",
    duration: 3,
    cost: { energy: 10 },
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },

  packGlimmerleaf: {
    label: "Pack Glimmerleaf",
    duration: 0,
    cost: {},
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },

  useHuntingLure: {
    label: "Use Hunting Lure",
    duration: 1,
    cost: { huntingLure: 1 },
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },

  meditate: {
    label: "Meditate",
    duration: 3,
    cost: { energy: 10 },
    auto: { resource: "mana", resumeAfterRest: true, restFallback: "campOnly" },
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },

  practiceManaCycling: {
    label: "Practice Mana Cycling",
    duration: 5,
    cost: { energy: 10, focus: 1, mana: 5 },
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },

  enterDungeon: {
    label: "Enter Ruin",
    duration: 0,
    cost: {},
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },

  leaveDungeon: {
    label: "Leave Ruin",
    duration: 0,
    cost: {},
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },
};

const skillDefinitions = {
  conditioning: {
    label: "Conditioning",
    progressLabel: "Distance traveled",
    capacityLabel: "Maximum Energy",
    revealAt: 50,
    ranks: [
      { rank: 0, threshold: 0, capacity: 40 },
      { rank: 1, threshold: 100, capacity: 50 },
      { rank: 2, threshold: 350, capacity: 60 },
      { rank: 3, threshold: 850, capacity: 70 },
      { rank: 4, threshold: 1850, capacity: 80 },
      { rank: 5, threshold: 3850, capacity: 90 },
      { rank: 6, threshold: 7850, capacity: 100 },
    ],
  },

  concentration: {
    label: "Concentration",
    progressLabel: "Deep Thought",
    capacityLabel: "Maximum Focus",
    revealAt: 5,
    ranks: [
      { rank: 0, threshold: 0, capacity: 3 },
      { rank: 1, threshold: 5, capacity: 4 },
      { rank: 2, threshold: 15, capacity: 5 },
      { rank: 3, threshold: 35, capacity: 6 },
      { rank: 4, threshold: 70, capacity: 7 },
      { rank: 5, threshold: 130, capacity: 8 },
    ],
  },

  manaCycling: {
    label: "Mana Cycling",
    progressLabel: "Successful cycles",
    capacityLabel: "Maximum Mana",
    ranks: [
      { rank: 0, threshold: 0, capacity: 10 },
      { rank: 1, threshold: 3, capacity: 12 },
      { rank: 2, threshold: 7, capacity: 14 },
      { rank: 3, threshold: 12, capacity: 16 },
      { rank: 4, threshold: 18, capacity: 18 },
      { rank: 5, threshold: 25, capacity: 20 },
    ],
  },

  meditation: {
    label: "Meditation",
    progressLabel: "Successful meditations",
    capacityLabel: "Meditate speed",
    capacitySuffix: "% faster",
    ranks: [
      { rank: 0, threshold: 0, capacity: 0 },
      { rank: 1, threshold: 5, capacity: 10 },
      { rank: 2, threshold: 15, capacity: 20 },
      { rank: 3, threshold: 35, capacity: 30 },
      { rank: 4, threshold: 70, capacity: 40 },
      { rank: 5, threshold: 130, capacity: 50 },
    ],
  },

  manaControl: {
    label: "Mana Control",
    progressLabel: "Mana spent casting",
    capacityLabel: "Control rank",
    ranks: [
      { rank: 0, threshold: 0, capacity: 0 },
      { rank: 1, threshold: 20, capacity: 1 },
      { rank: 2, threshold: 60, capacity: 2 },
      { rank: 3, threshold: 120, capacity: 3 },
    ],
  },
};

//State Engine
const gameState = {
  phase: "lost",

  autoAction: {
    actionName: null,
    pausedForRest: false,
  },

  activity: {
    active: false,
    kind: null,
    type: null,
    id: null,
    label: null,
    startTime: null,
    duration: 0,
    interval: false,
    context: null,
  },

  exploration: {
    currentStage: "findClearing",
    count: 0,
  },

  currentGoalId: "surviveTheWoods",

  selectedResearchEntry: null,
  journal: {
    entries: [],
  },

  world: {
    selectedRegion: "outskirts",
    regions: {
      outskirts: {
        unlocked: true,
        progress: 100,
        mastered: true,
        locations: ["Fibrous Plants", "Animal Trails", "Creepy Cave", "Abandoned Camp"],
      },
      north: {
        unlocked: false,
        progress: 0,
        mastered: false,
        locations: [],
      },
      east: {
        unlocked: false,
        progress: 0,
        mastered: false,
        locations: [],
      },
      south: {
        unlocked: false,
        progress: 0,
        mastered: false,
        locations: [],
      },
      west: {
        unlocked: false,
        progress: 0,
        mastered: false,
        locations: [],
      },
    },
  },

  discoveredClearing: false,
  discoveredStream: false,
  discoveredBerryBush: false,
  discoveredDeadfall: false,
  tier2Complete: false,
  knownOutskirtsPathsUnlocked: false,
  oldMapFound: false,
  tier3Unlocked: false,
  ruinedTorchFound: false,
  ruinedJournalFound: false,
  researchUnlocked: false,
  torchResearched: false,
  magicUnlocked: false,
  recallUnlocked: false,
  manaCrystalImbuingUnlocked: false,
  archiveDoorOpened: false,
  campAlchemyPlansFound: false,
  campTanningPlansFound: false,
  campSmeltingPlansFound: false,
  manaCondenserPlansFound: false,
  partialTowerPlansFound: false,

  magic: {
    sensedReveals: {},
    attunements: {
      capacity: 1,
      active: [],
    },
  },

  destination: null,

  hasCamp: false,

  skills: {
    conditioning: {
      rank: 0,
      distance: 0,
      pending: false,
      revealed: false,
    },

    concentration: {
      rank: 0,
      deepThought: 0,
      revealed: false,
    },

    manaCycling: {
      rank: 0,
      successfulCycles: 0,
      revealed: false,
    },

    meditation: {
      rank: 0,
      successfulMeditations: 0,
      revealed: false,
    },

    manaControl: {
      rank: 0,
      manaSpent: 0,
      revealed: false,
    },
  },

  expedition: {
    active: false,
    discoveredSomething: false,
    returning: false,
    returnPenalty: 0,
    completed: false,
    currentLocation: null,
    regionId: "outskirts",
    routeType: "open",
    distance: 0,
    targetDistance: 100,
    tonicSlots: [],

    dungeon: {
      active: false,
      dungeonId: null,
      nodeId: null,
    },

    carriedItems: {
      food: 0,
      fiber: 0,
      trap: 0,
    },
    carryCapacity: 5,

    water: 0,
    waterCapacity: 0,
  },
};
