// Mana Control is intentionally dormant. Set this back to true to reactivate
// the saved mana control progression, training entry, and spell bonuses.
const MANA_CONTROL_SYSTEM_ENABLED = false;
// Central balance point for the temporary gathering-speed benefit of tool Imbue.
const IMBUE_TOOL_SPEED_MULTIPLIER = 1.5;
const IMBUE_TOOL_CHARGES_PER_MANA = 5;

const resources = {
  energy: {
    label: "Energy",
    value: 0,
    maxValue: 10,
    perClick: 1,
    perSecond: 0,
    restPerSecond: 1,
    display: null,
    perClickDisplay: null,
    perSecondDisplay: null,
  },
  mana: {
    label: "Mana",
    value: 0,
    maxValue: 10,
    perClick: 1,
    perSecond: 0,
    display: null,
    perClickDisplay: null,
    perSecondDisplay: null,
  },
  focus: {
    label: "Focus",
    value: 0,
    maxValue: 3,
    perClick: 1,
    perSecond: 0,
    display: null,
    perClickDisplay: null,
    perSecondDisplay: null,
  },
  ward: {
    label: "Ward",
    value: 0,
    maxValue: 10,
    perClick: 0,
    perSecond: 0,
    hidden: true,
    display: null,
    perClickDisplay: null,
    perSecondDisplay: null,
  },
  manaCrystal: {
    label: "Mana Crystal",
    value: 0,
    maxValue: 100,
    perClick: 0,
    perSecond: 0,
    display: null,
    perClickDisplay: null,
    perSecondDisplay: null,
  },
  water: {
    label: "Water",
    value: 0,
    maxValue: 0,
    perClick: 1,
    perSecond: 0,
    display: null,
    perClickDisplay: null,
    perSecondDisplay: null,
  },
  food: {
    label: "Food",
    value: 0,
    maxValue: 100,
    perClick: 1,
    perSecond: 0,
    display: null,
    perClickDisplay: null,
    perSecondDisplay: null,
  },
  wood: {
    label: "Wood",
    value: 0,
    maxValue: 100,
    perClick: 1,
    perSecond: 0,
    display: null,
    perClickDisplay: null,
    perSecondDisplay: null,
  },
  fuel: {
    label: "Fuel",
    value: 0,
    maxValue: 2000,
    perClick: 0,
    perSecond: 0,
    hidden: true,
    display: null,
    perClickDisplay: null,
    perSecondDisplay: null,
  },
  imbuedWood: {
    label: "Imbued Wood",
    value: 0,
    maxValue: 500,
    perClick: 0,
    perSecond: 0,
    hidden: true,
    display: null,
    perClickDisplay: null,
    perSecondDisplay: null,
  },
  fiber: {
    label: "Fiber",
    value: 0,
    maxValue: 100,
    perClick: 1,
    perSecond: 0,
    display: null,
    perClickDisplay: null,
    perSecondDisplay: null,
  },
  trap: {
    label: "Trap",
    value: 0,
    maxValue: 5,
    perClick: 0,
    perSecond: 0,
    display: null,
    perClickDisplay: null,
    perSecondDisplay: null,
  },
  pelt: {
    label: "Pelt",
    value: 0,
    maxValue: 100,
    perClick: 0,
    perSecond: 0,
    display: null,
    perClickDisplay: null,
    perSecondDisplay: null,
  },
  stone: {
    label: "Stone",
    value: 0,
    maxValue: 100,
    perClick: 0,
    perSecond: 0,
    display: null,
    perClickDisplay: null,
    perSecondDisplay: null,
  },
  leather: {
    label: "Leather",
    value: 0,
    maxValue: 100,
    perClick: 0,
    perSecond: 0,
    display: null,
    perClickDisplay: null,
    perSecondDisplay: null,
  },
  ore: {
    label: "Ore",
    value: 0,
    maxValue: 100,
    perClick: 0,
    perSecond: 0,
    display: null,
    perClickDisplay: null,
    perSecondDisplay: null,
  },
  iron: {
    label: "Iron",
    value: 0,
    maxValue: 100,
    perClick: 0,
    perSecond: 0,
    display: null,
    perClickDisplay: null,
    perSecondDisplay: null,
  },
  steel: {
    label: "Steel",
    value: 0,
    maxValue: 100,
    perClick: 0,
    perSecond: 0,
    hidden: true,
    display: null,
    perClickDisplay: null,
    perSecondDisplay: null,
  },
  ironRing: {
    label: "Iron Ring",
    value: 0,
    maxValue: 20,
    perClick: 0,
    perSecond: 0,
    hidden: true,
    display: null,
    perClickDisplay: null,
    perSecondDisplay: null,
  },
  earthElementalCore: {
    label: "Earth Elemental Core",
    value: 0,
    maxValue: 100,
    perClick: 0,
    perSecond: 0,
    hidden: true,
    display: null,
    perClickDisplay: null,
    perSecondDisplay: null,
  },
  runedLeather: {
    label: "Runed Leather",
    value: 0,
    maxValue: 100,
    perClick: 0,
    perSecond: 0,
    hidden: true,
    display: null,
    perClickDisplay: null,
    perSecondDisplay: null,
  },
  naturalEssence: {
    label: "Natural Essence",
    value: 0,
    maxValue: 100,
    perClick: 0,
    perSecond: 0,
    hidden: true,
    display: null,
    perClickDisplay: null,
    perSecondDisplay: null,
  },
  nails: {
    label: "Nails",
    value: 0,
    maxValue: 100,
    perClick: 0,
    perSecond: 0,
    display: null,
    perClickDisplay: null,
    perSecondDisplay: null,
  },
  herb: {
    label: "Herb",
    value: 0,
    maxValue: 100,
    perClick: 0,
    perSecond: 0,
    display: null,
    perClickDisplay: null,
    perSecondDisplay: null,
  },
  glimmerleaf: {
    label: "Glimmerleaf",
    value: 0,
    maxValue: 50,
    perClick: 0,
    perSecond: 0,
    hidden: true,
    display: null,
    perClickDisplay: null,
    perSecondDisplay: null,
  },
  staminaTonic: {
    label: "Stamina Tonic",
    value: 0,
    maxValue: 20,
    perClick: 0,
    perSecond: 0,
    display: null,
    perClickDisplay: null,
    perSecondDisplay: null,
  },
  improvedStaminaTonic: {
    label: "Improved Stamina Tonic",
    value: 0,
    maxValue: 20,
    perClick: 0,
    perSecond: 0,
    hidden: true,
    display: null,
    perClickDisplay: null,
    perSecondDisplay: null,
  },
  manaTonic: {
    label: "Mana Tonic",
    value: 0,
    maxValue: 20,
    perClick: 0,
    perSecond: 0,
    hidden: true,
    display: null,
    perClickDisplay: null,
    perSecondDisplay: null,
  },
  majorManaTonic: {
    label: "Major Mana Tonic",
    value: 0,
    maxValue: 20,
    perClick: 0,
    perSecond: 0,
    hidden: true,
    display: null,
    perClickDisplay: null,
    perSecondDisplay: null,
  },
  huntingLure: {
    label: "Hunting Lure",
    value: 0,
    maxValue: 10,
    perClick: 0,
    perSecond: 0,
    hidden: true,
    display: null,
    perClickDisplay: null,
    perSecondDisplay: null,
  },
  staminaTonicBase: {
    label: "Stamina Tonic Base",
    value: 0,
    maxValue: 20,
    perClick: 0,
    perSecond: 0,
    display: null,
    perClickDisplay: null,
    perSecondDisplay: null,
  },
  manaTonicBase: {
    label: "Mana Tonic Base",
    value: 0,
    maxValue: 20,
    perClick: 0,
    perSecond: 0,
    hidden: true,
    display: null,
    perClickDisplay: null,
    perSecondDisplay: null,
  },
  concentratedTonicBase: {
    label: "Concentrated Tonic Base",
    value: 0,
    maxValue: 20,
    perClick: 0,
    perSecond: 0,
    hidden: true,
    display: null,
    perClickDisplay: null,
    perSecondDisplay: null,
  },
  concentratedManaTonicBase: {
    label: "Concentrated Mana Tonic Base",
    value: 0,
    maxValue: 20,
    perClick: 0,
    perSecond: 0,
    hidden: true,
    display: null,
    perClickDisplay: null,
    perSecondDisplay: null,
  },
  chargedCrystal: {
    label: "Charged Crystal",
    value: 0,
    maxValue: 100,
    perClick: 0,
    perSecond: 0,
    hidden: true,
    display: null,
    perClickDisplay: null,
    perSecondDisplay: null,
  },
  crudeIronPickHead: {
    label: "Pick Head",
    missingLabel: "Needs Pick Head",
    value: 0,
    maxValue: 1,
    perClick: 0,
    perSecond: 0,
    hidden: true,
    display: null,
    perClickDisplay: null,
    perSecondDisplay: null,
  },
  ironKnifeBlade: {
    label: "Knife Blade",
    missingLabel: "Needs Knife Blade",
    value: 0,
    maxValue: 1,
    perClick: 0,
    perSecond: 0,
    hidden: true,
    display: null,
    perClickDisplay: null,
    perSecondDisplay: null,
  },
  ironAxeHead: {
    label: "Axe Head",
    missingLabel: "Needs Axe Head",
    value: 0,
    maxValue: 1,
    perClick: 0,
    perSecond: 0,
    hidden: true,
    display: null,
    perClickDisplay: null,
    perSecondDisplay: null,
  },
};

const actions = {
  explore: {
    label: "Explore",
    duration: 1,
    cost: {
      energy: 5,
    },
    unlocked: true,
    running: false,

    button: null,
    progressBar: null,
    metaProgressBar: null,

    onStart: function () {},
    onComplete: function () {},
  },

  catchBreath: {
    label: "Catch Breath",
    duration: 1,
    cost: {},
    unlocked: true,
    running: false,

    button: null,
    progressBar: null,
    metaProgressBar: null,

    onStart: function () {},
    onComplete: function () {},
  },

  recover: {
    label: "Recover",
    duration: 3,
    cost: { energy: 5, food: 1 },
    auto: { resource: "focus", resumeAfterRest: true },
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },

  gatherWood: {
    label: "Gather Wood",
    duration: 1,
    cost: {
      energy: 4,
    },
    unlocked: false,
    running: false,
    auto: { resource: "wood", resumeAfterRest: true },

    button: null,
    progressBar: null,
    metaProgressBar: null,

    onStart: function () {},
    onComplete: function () {},
  },

  gatherFood: {
    label: "Gather Food",
    duration: 1.5,
    cost: {
      energy: 3,
    },
    unlocked: false,
    running: false,
    auto: { resource: "food", resumeAfterRest: true },

    button: null,
    progressBar: null,
    metaProgressBar: null,

    onStart: function () {},
    onComplete: function () {},
  },

  addWoodToFuel: {
    label: "Add Wood to Fuel",
    duration: 1,
    cost: {
      wood: 1,
    },
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },

  addImbuedWoodToFuel: {
    label: "Add Imbued Wood to Fuel",
    duration: 1,
    cost: {
      imbuedWood: 1,
    },
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },

  gatherWater: {
    label: "Gather Water",
    duration: 1,
    cost: {
      energy: 2,
    },
    unlocked: false,
    running: false,
    auto: { resource: "water", resumeAfterRest: true },

    button: null,
    progressBar: null,
    metaProgressBar: null,

    onStart: function () {},
    onComplete: function () {},
  },

  travel: {
    label: "Travel",
    duration: 1,
    cost: {},
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },

  packFood: {
    label: "Pack Food",
    duration: 0,
    cost: {
      food: 1,
    },
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },

  packWater: {
    label: "Pack Water",
    duration: 0,
    cost: {},
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },

  packStone: {
    label: "Pack Stone",
    duration: 0,
    cost: {
      stone: 1,
    },
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },

  packIron: {
    label: "Pack Iron",
    duration: 0,
    cost: {
      iron: 1,
    },
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },

  packChargedCrystal: {
    label: "Pack Charged Mana Crystal",
    duration: 0,
    cost: {
      chargedCrystal: 1,
    },
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },

  beginExpedition: {
    label: "Prepare for Expedition",
    duration: 0,
    cost: {},
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },

  exploreLocation: {
    label: "Explore Location",
    duration: 1,
    cost: {
      energy: 6,
    },
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },

  gatherFiber: {
    label: "Gather Fiber",
    duration: 1,
    cost: {
      energy: 1,
    },
    unlocked: false,
    running: false,
    auto: { carriedItem: "fiber" },
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },

  gatherHerbs: {
    label: "Gather Herbs",
    duration: 3,
    cost: {
      energy: 4,
    },
    unlocked: false,
    running: false,
    auto: { carriedItem: "herb" },
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },

  gatherGlimmerleaf: {
    label: "Gather Glimmerleaf",
    duration: 4,
    cost: {
      energy: 6,
    },
    unlocked: false,
    running: false,
    auto: { carriedItem: "glimmerleaf" },
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },

  concentrateTonicBase: {
    label: "Concentrate Tonic Base",
    duration: 3,
    cost: {},
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },

  concentrateManaTonicBase: {
    label: "Concentrate Mana Tonic Base",
    duration: 3,
    cost: {},
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },

  storeHerb: {
    label: "Store Herb",
    duration: 0,
    cost: {},
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },

  storeGlimmerleaf: {
    label: "Store Glimmerleaf",
    duration: 0,
    cost: {},
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },

  packHerb: {
    label: "Pack Herbs",
    duration: 0,
    cost: {},
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },

  returnToCamp: {
    label: "Return to Camp",
    duration: 1,
    cost: {},
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },

  packTrap: {
    label: "Pack Trap",
    duration: 0,
    cost: {
      trap: 1,
    },
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },
  packPelt: {
    label: "Pack Pelt",
    duration: 0,
    cost: {
      pelt: 1,
    },
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },

  storePelt: {
    label: "Store Pelt",
    duration: 0,
    cost: {},
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },

  takeLeather: {
    label: "Take Leather",
    duration: 0,
    cost: {},
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },

  packWood: {
    label: "Pack Wood",
    duration: 0,
    cost: {
      wood: 1,
    },
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },

  storeWood: {
    label: "Store Fuel",
    duration: 0,
    cost: {},
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },

  packImbuedWood: {
    label: "Pack Imbued Wood",
    duration: 0,
    cost: {
      imbuedWood: 1,
    },
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },

  packOre: {
    label: "Pack Ore",
    duration: 0,
    cost: {
      ore: 1,
    },
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },

  storeOre: {
    label: "Store Ore",
    duration: 0,
    cost: {},
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },

  takeIron: {
    label: "Take Iron",
    duration: 0,
    cost: {},
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },

  mineStone: {
    label: "Mine Stone",
    duration: 1,
    cost: {
      energy: 1,
    },
    unlocked: false,
    running: false,
    auto: { carriedItem: "stone" },
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },

  mineIron: {
    label: "Mine Iron",
    duration: 5,
    cost: {
      energy: 6,
    },
    unlocked: false,
    running: false,
    auto: { carriedItem: "iron" },
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },
  investigateNorthernDisturbance: {
    label: "Investigate the Tremors",
    duration: 0,
    cost: {},
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },
  challengeEarthElemental: {
    label: "Challenge Earth Elemental",
    duration: 0,
    cost: {},
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },
  investigateEasternDisturbance: {
    label: "Investigate the Eastern Disturbance",
    duration: 0,
    cost: {},
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },
  challengeThornfang: {
    label: "Challenge Thornfang",
    duration: 0,
    cost: {},
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },
  investigateSouthernDisturbance: {
    label: "Investigate the Southern Disturbance",
    duration: 0,
    cost: {},
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },
  challengeBlightedBriar: {
    label: "Challenge Blighted Briar",
    duration: 0,
    cost: {},
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },

  setTrap: {
    label: "Set Trap",
    duration: 1,
    cost: {
      energy: 7,
    },
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },
  checkTrap: {
    label: "Check Trap",
    duration: 1,
    cost: {
      energy: 2,
    },
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },
  scoutTrapSite: {
    label: "Scout Trail",
    duration: 1,
    cost: {
      energy: 5,
    },
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },
  gatherStone: {
    label: "Gather Stone",
    duration: 1,
    cost: {
      energy: 2,
    },
    unlocked: false,
    running: false,
    auto: { carriedItem: "stone" },
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },
  trackGame: {
    label: "Track Game",
    duration: 2,
    cost: { energy: 6 },
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },

  huntGame: {
    label: "Hunt Game",
    duration: 3,
    cost: { energy: 8 },
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },

  packGlimmerleaf: {
    label: "Pack Glimmerleaf",
    duration: 0,
    cost: {},
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },

  useHuntingLure: {
    label: "Use Hunting Lure",
    duration: 1,
    cost: { huntingLure: 1 },
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },

  meditate: {
    label: "Meditate",
    duration: 3,
    cost: { energy: 10 },
    auto: { resource: "mana", resumeAfterRest: true, restFallback: "campOnly" },
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },

  practiceManaCycling: {
    label: "Practice Mana Cycling",
    duration: 5,
    cost: { energy: 10, focus: 1, mana: 5 },
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },

  enterDungeon: {
    label: "Enter Ruin",
    duration: 0,
    cost: {},
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },

  leaveDungeon: {
    label: "Leave Ruin",
    duration: 0,
    cost: {},
    unlocked: false,
    running: false,
    button: null,
    progressBar: null,
    metaProgressBar: null,
    onStart: function () {},
    onComplete: function () {},
  },
};

const skillDefinitions = {
  conditioning: {
    label: "Conditioning",
    progressLabel: "Distance traveled",
    capacityLabel: "Maximum Energy",
    rank2ProgressLabel: "Reinforced energy spent",
    revealAt: 50,
    ranks: [
      {
        rank: 1,
        levels: [
          { level: 0, threshold: 0, capacity: 40 },
          { level: 1, threshold: 100, capacity: 50 },
          { level: 2, threshold: 350, capacity: 60 },
          { level: 3, threshold: 850, capacity: 70 },
          { level: 4, threshold: 1850, capacity: 80 },
          { level: 5, threshold: 3850, capacity: 90 },
          { level: 6, threshold: 7850, capacity: 100 },
        ],
      },
      {
        rank: 2,
        levels: [
          { level: 0, threshold: 0, capacity: 100, reinforcedBodyBonus: 25 },
          { level: 1, threshold: 150, capacity: 100, reinforcedBodyBonus: 33 },
          { level: 2, threshold: 350, capacity: 100, reinforcedBodyBonus: 40 },
          { level: 3, threshold: 650, capacity: 100, reinforcedBodyBonus: 48 },
          { level: 4, threshold: 1050, capacity: 100, reinforcedBodyBonus: 55 },
          { level: 5, threshold: 1550, capacity: 100, reinforcedBodyBonus: 63 },
          { level: 6, threshold: 2200, capacity: 100, reinforcedBodyBonus: 70 },
          { level: 7, threshold: 3000, capacity: 100, reinforcedBodyBonus: 78 },
          { level: 8, threshold: 4000, capacity: 100, reinforcedBodyBonus: 85 },
          { level: 9, threshold: 5250, capacity: 100, reinforcedBodyBonus: 93 },
          { level: 10, threshold: 6750, capacity: 100, reinforcedBodyBonus: 100 },
        ],
      },
    ],
  },

  concentration: {
    label: "Concentration",
    progressLabel: "Deep Thought",
    capacityLabel: "Maximum Focus",
    revealAt: 5,
    ranks: [
      {
        rank: 1,
        levels: [
          { level: 0, threshold: 0, capacity: 3 },
          { level: 1, threshold: 5, capacity: 4 },
          { level: 2, threshold: 15, capacity: 5 },
          { level: 3, threshold: 35, capacity: 6 },
          { level: 4, threshold: 70, capacity: 7 },
          { level: 5, threshold: 130, capacity: 8 },
        ],
      },
    ],
  },

  manaCycling: {
    label: "Mana Cycling",
    progressLabel: "Mana spent",
    rank2ProgressLabel: "Mana spent",
    capacityLabel: "Maximum Mana",
    ranks: [
      {
        rank: 1,
        levels: [
          { level: 0, threshold: 0, capacity: 3 },
          { level: 1, threshold: 5, capacity: 5, breakthrough: true },
          { level: 2, threshold: 15, capacity: 8, breakthrough: true },
          { level: 3, threshold: 25, capacity: 11, breakthrough: true },
          { level: 4, threshold: 35, capacity: 15, breakthrough: true },
          { level: 5, threshold: 50, capacity: 20, breakthrough: true },
        ],
      },
      {
        rank: 2,
        levels: [
          { level: 0, threshold: 100, capacity: 20 },
          { level: 1, threshold: 125, capacity: 25 },
          { level: 2, threshold: 150, capacity: 30 },
          { level: 3, threshold: 175, capacity: 36 },
          { level: 4, threshold: 200, capacity: 42 },
          { level: 5, threshold: 250, capacity: 50, breakthrough: true },
          { level: 6, threshold: 300, capacity: 58 },
          { level: 7, threshold: 350, capacity: 67 },
          { level: 8, threshold: 400, capacity: 77 },
          { level: 9, threshold: 450, capacity: 88 },
          { level: 10, threshold: 500, capacity: 100, breakthrough: true },
        ],
      },
    ],
  },

  meditation: {
    label: "Meditation",
    progressLabel: "Successful meditations",
    rank2ProgressLabel: "Attuned meditations",
    capacityLabel: "Meditate speed",
    capacitySuffix: "% faster",
    ranks: [
      {
        rank: 1,
        levels: [
          { level: 0, threshold: 0, capacity: 0 },
          { level: 1, threshold: 5, capacity: 10 },
          { level: 2, threshold: 15, capacity: 20 },
          { level: 3, threshold: 35, capacity: 30 },
          { level: 4, threshold: 70, capacity: 40 },
          { level: 5, threshold: 130, capacity: 50 },
        ],
      },
      {
        rank: 2,
        levels: [
          { level: 0, threshold: 0, capacity: 50, manaRestore: 1, energyCost: 5 },
          { level: 1, threshold: 8, capacity: 55, manaRestore: 2, energyCost: 4 },
          { level: 2, threshold: 20, capacity: 60, manaRestore: 2, energyCost: 4 },
          { level: 3, threshold: 38, capacity: 65, manaRestore: 3, energyCost: 3 },
          { level: 4, threshold: 62, capacity: 70, manaRestore: 3, energyCost: 3 },
          { level: 5, threshold: 95, capacity: 75, manaRestore: 3, energyCost: 2 },
          { level: 6, threshold: 140, capacity: 80, manaRestore: 4, energyCost: 2 },
          { level: 7, threshold: 200, capacity: 83, manaRestore: 4, energyCost: 1 },
          { level: 8, threshold: 275, capacity: 86, manaRestore: 4, energyCost: 1 },
          { level: 9, threshold: 370, capacity: 88, manaRestore: 4, energyCost: 1 },
          { level: 10, threshold: 500, capacity: 90, manaRestore: 5, energyCost: 1 },
        ],
      },
    ],
  },

  manaControl: {
    label: "Mana Control",
    progressLabel: "Mana spent casting",
    capacityLabel: "Control level",
    ranks: [
      {
        rank: 1,
        levels: [
          { level: 0, threshold: 0, capacity: 0 },
          { level: 1, threshold: 20, capacity: 1 },
          { level: 2, threshold: 60, capacity: 2 },
          { level: 3, threshold: 120, capacity: 3 },
        ],
      },
    ],
  },
};

//State Engine
const gameState = {
  phase: "lost",

  autoAction: {
    actionName: null,
    pausedForRest: false,
  },

  activity: {
    active: false,
    kind: null,
    type: null,
    id: null,
    mode: null,
    label: null,
    startTime: null,
    duration: 0,
    interval: false,
    context: null,
  },

  // Combat is intentionally transient: save/load always returns to normal play.
  combat: {
    active: false,
    resolved: false,
    enemyId: null,
    enemyHealth: 0,
    enemyMaxHealth: 0,
    nextAttackTime: null,
    nextAbilityTime: null,
    ability: null,
    cast: null,
    rewardGranted: false,
    reward: null,
    storyEncounter: false,
    resultMessage: "",
  },

  exploration: {
    currentStage: "findClearing",
    count: 0,
  },

  currentGoalId: "surviveTheWoods",

  selectedResearchEntry: null,
  // Major destinations track whether their first unlock has been announced and visited.
  systemUnlocks: {
    initialized: false,
    announced: {},
    seen: {},
  },
  journal: {
    entries: [],
  },

  world: {
    selectedRegion: "outskirts",
    regions: {
      outskirts: {
        unlocked: true,
        progress: 100,
        mastered: true,
        locations: ["Fibrous Plants", "Animal Trails", "Creepy Cave", "Abandoned Camp"],
      },
      north: {
        unlocked: false,
        progress: 0,
        mastered: false,
        locations: [],
      },
      east: {
        unlocked: false,
        progress: 0,
        mastered: false,
        locations: [],
      },
      south: {
        unlocked: false,
        progress: 0,
        mastered: false,
        locations: [],
      },
      west: {
        unlocked: false,
        progress: 0,
        mastered: false,
        locations: [],
      },
    },
  },

  discoveredClearing: false,
  discoveredStream: false,
  discoveredBerryBush: false,
  discoveredDeadfall: false,
  tier2Complete: false,
  knownOutskirtsPathsUnlocked: false,
  oldMapFound: false,
  tier3Unlocked: false,
  ruinedTorchFound: false,
  ruinedJournalFound: false,
  researchUnlocked: false,
  torchResearched: false,
  magicUnlocked: false,
  recallUnlocked: false,
  manaCrystalImbuingUnlocked: false,
  archiveDoorOpened: false,
  campAlchemyPlansFound: false,
  campTanningPlansFound: false,
  campSmeltingPlansFound: false,
  manaCondenserPlansFound: false,
  partialTowerPlansFound: false,
  towerConstructionUnlocked: false,
  towerBasementCompleted: false,
  tower: {
    selectedId: "heart",
    lastAutoSelectedProject: "",
  },
  personalWardUnlocked: false,
  personalWardPopupShown: false,
  combatVictories: 0,
  northernDisturbance: {
    triggered: false,
    resolved: false,
    popupShown: false,
  },
  regionalProgress: {
    unlocked: false,
    east: {
      disturbanceTriggered: false,
      disturbanceResolved: false,
      capabilityDiscovered: false,
    },
    south: {
      disturbanceTriggered: false,
      disturbanceResolved: false,
      capabilityDiscovered: false,
    },
  },

  magic: {
    sensedReveals: {},
    toolCharges: {
      knife: 0,
      axe: 0,
      pick: 0,
    },
    spellProgress: {
      manaSense: {
        xp: 0,
        level: 0,
      },
      attunement: {
        xp: 0,
        level: 0,
      },
      imbue: {
        xp: 0,
        level: 0,
      },
      arcaneForce: {
        xp: 0,
        level: 0,
      },
      ward: {
        xp: 0,
        level: 0,
      },
    },
    ward: {
      rank: 1,
      formed: false,
      maintainEnabled: false,
    },
    attunements: {
      capacity: 1,
      active: [],
      rank: 1,
      rankTwoLevel: 0,
      rankTwoXp: 0,
      breakthroughs: {},
      persistentResonanceCompleted: false,
      rankTwoComplete: false,
    },
    imbuement: {
      rank: 1,
      rankTwoLevel: 0,
      rankTwoXp: 0,
      breakthroughs: {},
      permanentBindingCompleted: false,
      rankTwoComplete: false,
      craftedRings: {},
      equippedRing: null,
      backpackImbued: false,
      equipmentEnchantments: {},
      furnaceTier: 0,
      alchemyTier: 0,
      controlMatrixStage: 0,
      controlCapacity: 5,
    },
    arcaneForce: {
      rank: 1,
      rankTwoLevel: 0,
      rankTwoXp: 0,
      breakthroughs: {},
      forceAmplificationCompleted: false,
      rankTwoComplete: false,
    },
  },

  destination: null,

  hasCamp: false,

  skills: {
    conditioning: {
      rank: 1,
      level: 0,
      distance: 0,
      reinforcedEnergyUnlockSpent: 0,
      reinforcedEnergySpent: 0,
      pending: false,
      revealed: false,
    },

    concentration: {
      rank: 1,
      level: 0,
      deepThought: 0,
      revealed: false,
    },

    manaCycling: {
      rank: 1,
      level: 0,
      manaXp: 0,
      breakthroughReady: false,
      successfulCycles: 0,
      deepCycles: 0,
      revealed: false,
    },

    meditation: {
      rank: 1,
      level: 0,
      successfulMeditations: 0,
      attunedMeditations: 0,
      revealed: false,
    },

    manaControl: {
      rank: 1,
      level: 0,
      manaSpent: 0,
      revealed: false,
    },
  },

  projects: {
    towerFoundation: {
      unlocked: false,
      completed: false,
      level: 0,
      work: 0,
      deposits: {},
    },
    towerBasement: {
      unlocked: false,
      completed: false,
      level: 0,
      work: 0,
      deposits: {},
    },
  },

  towerNodes: {
    north: {
      activated: false,
      researchUnlocked: false,
      built: false,
      deposits: {
        stone: 0,
        iron: 0,
        chargedCrystal: 0,
      },
      imbueProgress: 0,
      threadSenseProgress: 0,
      threadSensed: false,
      advancedRecallUnlocked: false,
      permanentImbued: false,
    },
    east: {
      activated: false,
      researchUnlocked: false,
      built: false,
      deposits: {},
      imbueProgress: 0,
      threadSenseProgress: 0,
      threadSensed: false,
      advancedRecallUnlocked: false,
      permanentImbued: false,
    },
    south: {
      activated: false,
      researchUnlocked: false,
      built: false,
      deposits: {},
      imbueProgress: 0,
      threadSenseProgress: 0,
      threadSensed: false,
      advancedRecallUnlocked: false,
      permanentImbued: false,
    },
  },

  elementals: {
    earth: {
      owned: 0,
      bindingDiscovered: false,
      assignments: {
        tower: 0,
        nodes: {
          north: {
            stone: 0,
            iron: 0,
          },
        },
      },
      cycles: {
        nodes: {
          north: {
            stone: { remaining: 0 },
            iron: { remaining: 0 },
          },
        },
      },
      capabilities: {
        equipmentUnlocked: false,
        attunementUnlocked: false,
        harnesses: {},
        attunements: {},
      },
    },
  },

  expedition: {
    active: false,
    discoveredSomething: false,
    completed: false,
    currentLocation: null,
    regionId: "outskirts",
    routeType: "open",
    distance: 0,
    targetDistance: 100,
    tonicSlots: [],
    locationSpellEffects: {},

    dungeon: {
      active: false,
      dungeonId: null,
      nodeId: null,
    },

    carriedItems: {
      food: 0,
      fiber: 0,
      trap: 0,
    },
    carryCapacity: 5,

    water: 0,
    waterCapacity: 0,
  },
};
